### ISSUE TITLE
crash while travelling the world

### ISSUE THREAD

**Issue by 0Navis0** [ArtixAllMighty/Rpg-Addon-Beastmaster#1]
I get this crash while travelling the world. I use Minecraft 1.11.2 and Forge 13.20.0.2310. https://pastebin.com/vjfqEv82

**Comment by AbsolemJackdaw** [comment]
have you tried both updating the SubLib and the BeastMaster Mod ? (and any other of my mods) to the latest version ? 
the fix where you crouch and the game crashes with 'EventBeastmasterAttraction' should have been fixed since [1.1.0.1 (click to view fix)](https://github.com/ArtixAllMighty/Rpg-Addon-Beastmaster/commit/53f026eada3d4ee0b935d7ef4943d9154fe35498#diff-90cd4b85e139255b71c07ea3f13e52f5L49)

**Comment by AbsolemJackdaw** [comment]
absence of answer concludes to a resolved issue.
closing now.
